/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DNS_H
#define DNS_H

/*
 * function declarations 
 */
void            init_DNS(void);
Netsnmp_Node_Handler handle_DnsQps;

#endif                          /* DNS_H */
