/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "DEV.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>

int get_mem_useage(){
		int fd = open("/proc/meminfo",O_RDONLY);
		if(fd < 0){
				return 0;
		}
		char* buf = calloc(1,1024*10);
		if(buf == NULL){
				return 0;
		}
		int size = read(fd,buf,1024*10);
		if(size <= 0){
				return 0;
		}

		int mem_free = 0,mem_total = 0;
		char tmpbuf1[32],tmpbuf2[32];

		char*ptotal = strstr(buf,"MemTotal:");
		if(NULL == ptotal){
				return 0;
		}
		sscanf(ptotal,"%s%d%s",tmpbuf1,&mem_total,tmpbuf2);

		char*pfree = strstr(buf,"MemFree:");
		if(NULL == pfree){
				return 0;
		}
		sscanf(pfree,"%s%d%s",tmpbuf1,&mem_free,tmpbuf2);

		free(buf);
		close(fd);
		return 100 - (mem_free* 100  / mem_total);
}

int get_cpu_useage(){
		FILE* fp = popen("top -bn 1","r");
		if(NULL == fp){
				return 0;
		}
		char buf[1025] = {'\0'};
		if(buf == NULL){
				pclose(fp);
				return 0;
		}

		int size = fread(buf,1024,1,fp);
		if(size <= 0){
				pclose(fp);
				return 0;
		}

		char* p_buf = strstr(buf,"id,");
		char tmp[32] = {'\0'};
		strncpy(tmp,p_buf-5,2);

		pclose(fp);
		return 100 - atoi(tmp);
}


/** Initializes the DEV module */
void
init_DEV(void)
{
    const oid       Cpu5s_oid[] = { 1, 3, 6, 1, 4, 1, 47032, 3, 1, 1 };
    const oid       MemoryUsage_oid[] =
        { 1, 3, 6, 1, 4, 1, 47032, 3, 2, 1 };

    DEBUGMSGTL(("DEV", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("Cpu5s", handle_Cpu5s, Cpu5s_oid,
                             OID_LENGTH(Cpu5s_oid), HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("MemoryUsage", handle_MemoryUsage,
                             MemoryUsage_oid, OID_LENGTH(MemoryUsage_oid),
                             HANDLER_CAN_RONLY));
}

int
handle_Cpu5s(netsnmp_mib_handler *handler,
             netsnmp_handler_registration *reginfo,
             netsnmp_agent_request_info *reqinfo,
             netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

	int  cpu = get_cpu_useage();
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &cpu,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(cpu));
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_Cpu5s\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_MemoryUsage(netsnmp_mib_handler *handler,
                   netsnmp_handler_registration *reginfo,
                   netsnmp_agent_request_info *reqinfo,
                   netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
	int mem = get_mem_useage();
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &mem,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(mem));
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_MemoryUsage\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
