/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEV_H
#define DEV_H

/*
 * function declarations 
 */
void            init_DEV(void);
Netsnmp_Node_Handler handle_Cpu5s;
Netsnmp_Node_Handler handle_MemoryUsage;
Netsnmp_Node_Handler handle_PowerInfo;
Netsnmp_Node_Handler handle_FanInfo;

#endif                          /* DEV_H */
