/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DHCP_H
#define DHCP_H

/*
 * function declarations 
 */
void            init_DHCP(void);
Netsnmp_Node_Handler handle_DhcpLps;
Netsnmp_Node_Handler handle_DhcpQps;

#endif                          /* DHCP_H */
