/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "DHCP.h"

#include <stdio.h>
#include <string.h>

int get_dhcp_qps()
{
		FILE* fp = popen("cat /dev/shm/dhcp-d/business | grep request","r");
		if(NULL == fp)
		{
				return 0;
		}
		char cmd_res[1024] = {'\0'};
		int len = fread(cmd_res,1024,1,fp);
		if(len <= 0)
		{
				pclose(fp);
				return 0;
		}
		int str_len = strlen(cmd_res);
		if(str_len <= 0)
		{
				pclose(fp);
				return 0;
		}

		char *p_data = strchr(cmd_res,' ');
		if(NULL != p_data)
		{
				p_data += 1;
				pclose(fp);
				return atoi(p_data) / 60;
		}
		pclose(fp);
		return -1;
}

int get_dhcp_lps()
{
		FILE* fp = popen("cat /dev/shm/dhcp-d/business | grep ack","r");
		if(NULL == fp)
		{
				return -1;
		}
		char cmd_res[1024] = {'\0'};
		int len = fread(cmd_res,1024,1,fp);
		if(len <= 0)
		{
				pclose(fp);
				return 0;
		}
		int str_len = strlen(cmd_res);
		if(str_len <= 0)
		{
				pclose(fp);
				return 0;
		}

		char *p_data = strchr(cmd_res,' ');
		if(NULL != p_data)
		{
				p_data += 1;
				pclose(fp);
				return atoi(p_data) / 60;
		}
		pclose(fp);
		return 0;
}

/** Initializes the DHCP module */
void
init_DHCP(void)
{
    const oid       DhcpLps_oid[] =
        { 1, 3, 6, 1, 4, 1, 47032, 5, 1, 1, 1 };
    const oid       DhcpQps_oid[] =
        { 1, 3, 6, 1, 4, 1, 47032, 5, 1, 2, 3 };

    DEBUGMSGTL(("DHCP", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("DhcpLps", handle_DhcpLps, DhcpLps_oid,
                             OID_LENGTH(DhcpLps_oid), HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("DhcpQps", handle_DhcpQps, DhcpQps_oid,
                             OID_LENGTH(DhcpQps_oid), HANDLER_CAN_RONLY));
}

int
handle_DhcpLps(netsnmp_mib_handler *handler,
               netsnmp_handler_registration *reginfo,
               netsnmp_agent_request_info *reqinfo,
               netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

	int lps = get_dhcp_qps();
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &lps,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(lps));
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_DhcpLps\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_DhcpQps(netsnmp_mib_handler *handler,
               netsnmp_handler_registration *reginfo,
               netsnmp_agent_request_info *reqinfo,
               netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

	int qps = get_dhcp_qps();
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &qps,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(qps));
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_DhcpQps\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
