/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "DNS.h"

#include <stdio.h>
#include <string.h>

int get_dns_qps()
{
		FILE* fp = popen("cat /sys/kernel/nap/stat | grep receive_accept","r");
		if(NULL == fp)
		{
				//printf("popen(cat /sys/kernel/nap/stat | grep receive_accept) error\n");
				return 0;
		}
		char cmd_res[1024] = {'\0'};
		int len = fread(cmd_res,1024,1,fp);
		if(len <= 0)
		{
				pclose(fp);
				return 0;
		}
		int str_len = strlen(cmd_res);
		if(str_len <= 0)
		{
				pclose(fp);
				//printf("%d-debug\n",__LINE__);
				return 0;
		}
		//printf("len=%d,str_len=%d\n",len,str_len);
		//printf("%s\n",res);
		char*p_buf = cmd_res;
		char*p_tmp = cmd_res;
		char* p_data = NULL;
		int sum = 0;

		while(*p_buf++)
		{
				if(*p_buf == '\n')
				{
						*p_buf = '\0';

						//printf("%s\n",p_tmp);
						p_data = strrchr(p_tmp,' ');
						if(NULL != p_data)
						{
								p_data += 1;
								sum += atoi(p_data);
						}
						p_buf++;
						p_tmp = p_buf;
				}
		}

		pclose(fp);
		return sum;
}


/** Initializes the DNS module */
void
init_DNS(void)
{
    const oid       DnsQps_oid[] =
        { 1, 3, 6, 1, 4, 1, 47032, 4, 1, 1, 1, 1, 1 };

    DEBUGMSGTL(("DNS", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("DnsQps", handle_DnsQps, DnsQps_oid,
                             OID_LENGTH(DnsQps_oid), HANDLER_CAN_RONLY));
}

int
handle_DnsQps(netsnmp_mib_handler *handler,
              netsnmp_handler_registration *reginfo,
              netsnmp_agent_request_info *reqinfo,
              netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

	int qps = get_dns_qps();
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &qps,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(qps));
        break;


    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR, "unknown mode (%d) in handle_DnsQps\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
